experiment:
  dataset: amazon_music
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset_reduced.tsv
  prefiltering:
   - strategy: global_threshold
     threshold: 4
   - strategy: iterative_k_core
     core: 5
  binarize: True
  splitting:
    save_on_disk: True
    save_folder: ../data/{0}/splitting/
    test_splitting:
      test_ratio: 0.2
      strategy: random_subsampling
      folds: 5
  top_k: 50
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCG, MAP, MRR, Precision, Recall,F1,HR]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    ConvNeuMF:
      epochs: [30]
      batch_size: [16, 32] 
      embedding_size: [16, 32]
      lr: [0.0001, 0.0005, 0.001]
      l_w: [0.0001, 0.0005, 0.001]
      l_b: [0.01, 0.001, 0.0001]
      cnn_channels: (1, 16, 16)
      cnn_kernels: (2,2)
      cnn_strides: (2,2)
      dropout_prob: [0.7]
      meta:
        verbose: True
        hyper_max_evals: 30
        hyper_opt_alg: tpe
        save_recs: True
