experiment:
  dataset: epinions
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset.tsv
  prefiltering:
  - strategy: iterative_k_core
    core: 2
  binarize: true
  splitting:
    save_on_disk: true
    save_folder: ../data/{0}/splitting/
    test_splitting:
      test_ratio: 0.2
      strategy: random_subsampling
      folds: 5
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [nDCG, MAP, MRR, Precision, Recall, F1, HR]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    GMF:
      meta:
        verbose: true
        save_recs: true
        epochs: 40
        batch_size: 512
        mf_factors: 256
        lr: 0.0003568284261458735
        is_edge_weight_train: true
    NeuMF: #from the original paper + Rendle
      meta:
        verbose: true
        save_recs: true
      mf_factors: 256
      dropout: 0
      is_mf_train: true
      is_mlp_train: true
      batch_size: 256
      epochs: 10
      lr: 0.5
      m: [8]
    MultiVAE:
      meta:
        verbose: true
        save_recs: true
      lr: 0.6
      epochs: 10
      batch_size: 256
      intermediate_dim: 800
      latent_dim: 400
      dropout_pkeep: 0.5
      reg_lambda: 0.6
    NGCF:
      meta:
        save_recs: true
      lr: 0.09
      epochs: 15
      batch_size: 512
      factors: 64
      l_w: 0.4
      weight_size: (64,)
      node_dropout: ()
      message_dropout: (0.4,)
    MultiDAE:
      meta:
        save_recs: true
        verbose: true
      epochs: 5
      batch_size: 1024
      intermediate_dim: 600
      latent_dim: 200
      reg_lambda: 0.6
      lr: 0.7
      dropout_pkeep: 1
    ConvNeuMF:
      meta:
        save_recs: true
        verbose: true
      epochs: 10
      batch_size: 16
      embedding_size: 50
      lr: 0.05
      l_w: 0.08
      l_b: 0.07
      cnn_channels: (1, 16, 16)
      cnn_kernels: (2,2)
      cnn_strides: (2,2)
      dropout_prob: 0.5
    ConvMF:
      meta:
        save_recs: true
        verbose: true
      epochs: 10
      batch_size: 32
      embedding_size: 100
      lr: 0.05
      l_w: 0.03
      l_b: 0.04
      cnn_channels: (1, 32, 32)
      cnn_kernels: (2,2)
      cnn_strides: (2,2)
      dropout_prob: 0.4
    EASER:
      meta:
        verbose: true
        save_recs: true
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      l2_norm: : 174.1791207224706
  path_output_rec_result: ./results/Untuned_epinions/run_30
  path_output_rec_weight: ./weights/Untuned_epinions/run_30
  path_output_rec_performance: ./performance/Untuned_epinions/run_30
  path_log_folder: ./logs/Untuned_epinions/run_30
